version: "3.1"
services:
  web:
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"  # Puerto para live chat/longpolling
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=myodoo
      - POSTGRES_DB=postgres
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons          # Módulos personalizados
      - ./enterprise:/mnt/enterprise-addons # Módulos Enterprise (opcional)
      - ./config:/etc/odoo                  # Archivos de configuración
    restart: always

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    restart: always
    command: postgres -c 'max_connections=200'

volumes:
  odoo-web-data:
  odoo-db-data: